/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1802c872-b4d3-4982-949a-87d53e83032c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_eQzaZF1YX",
    "aws_user_pools_web_client_id": "3bi1squ7jv7sk69iejinfso905",
    "oauth": {}
};


export default awsmobile;
